// Auto-generated by scripts/gen_swift_calibration.py.
// Source: calibration_heuristic_2026-04-18.json
// Source type: heuristic
// Generated: 2026-04-18T21:14:27
// Do not edit by hand — re-run calibration to refresh.
import Foundation

/// Chars-per-token ratios per content category. Hand-derived from tokenizer literature and sample observations (NOT measured via count_tokens API). Replace with measured values once API credits are available by re-running scripts/calibrate.py.
///
/// Used to estimate tokens from file char counts at runtime
/// **without any network call**.
///
/// The ratio is applied as: `estimatedTokens = chars / mean`.
/// Fidelity band ±13.8% (worst-case stddev/mean).
enum BakedCalibration {

    struct Ratio: Sendable, Equatable {
        let mean: Double
        let stddev: Double
        let min: Double
        let max: Double
        let n: Int

        /// Estimate tokens from raw char count using this ratio.
        func estimateTokens(chars: Int) -> Int {
            guard mean > 0 else { return chars / 3 }
            return Swift.max(0, Int(Double(chars) / mean))
        }

        /// 95% CI half-width assuming normality. Use to render ± ranges.
        func confidenceHalfWidth(chars: Int) -> Int {
            guard n > 1, stddev > 0, mean > 0 else { return 0 }
            let tokens = Double(chars) / mean
            let relativeStddev = stddev / mean
            return Int(tokens * relativeStddev * 1.96)
        }
    }

    enum Category: String, Sendable, CaseIterable {
        case skillMarkdown
        case claudeMdProse
        case mcpToolSchema
        case systemReminder
    }

    /// Model the calibration was measured against.
    static let model: String = "claude-opus-4-7"

    /// Date the calibration was generated (ISO-8601).
    static let generatedAt: String = "2026-04-18T20:45:00"

    static let skillMarkdownRatio = Ratio(mean: 2.9000, stddev: 0.4000, min: 2.0000, max: 3.8000, n: 0)
    static let claudeMdProseRatio = Ratio(mean: 3.3000, stddev: 0.3000, min: 2.8000, max: 3.8000, n: 0)
    static let mcpToolSchemaRatio = Ratio(mean: 3.8000, stddev: 0.2500, min: 3.4000, max: 4.2000, n: 0)
    static let systemReminderRatio = Ratio(mean: 3.1000, stddev: 0.3500, min: 2.5000, max: 3.7000, n: 0)

    static let ratios: [Category: Ratio] = [
        .skillMarkdown: skillMarkdownRatio,
        .claudeMdProse: claudeMdProseRatio,
        .mcpToolSchema: mcpToolSchemaRatio,
        .systemReminder: systemReminderRatio,
    ]

    /// Convenience: estimate tokens for a given category + char count.
    /// Falls back to chars/3 if the category has no calibration (shouldn't
    /// happen in practice; `ratios` covers all cases).
    static func estimate(_ chars: Int, as category: Category) -> Int {
        (ratios[category] ?? Ratio(mean: 3, stddev: 0, min: 3, max: 3, n: 0))
            .estimateTokens(chars: chars)
    }
}
